### PR TITLE
Ensure blank line between original message and extra

### LINKED ISSUE #31: Encrypted timestamp can end up in second line of commit message
git-privacy currently doesn't ensure that the encrypted timestamp doesn't end up in the second line of the commit message.
This will lead some tools to assume that it's part of the commit title and will be shown as such.

I think the problem in my case is that JGit doesn't add an empty newline to a commit message that only contains a title line.

Would be great to ensure that the `Git-Privacy` line always has at least one empty line above?

### PR DESCRIPTION
**Pull request by cburkert**
Should fix #31

### CODE REVIEW

**Comment by cburkert** [comment]
@fapdash Does this fix the issue? I assume JGit does not end its commit messages with a newline like Git does.

**Comment by fapdash** [comment]
How do I test this locally?

I tried

```
~/repos/git-privacy$ python3 setup.py install --user
```

But then gitprivacy seems to be broken:

```
$ git-privacy redate --only-head
Traceback (most recent call last):
  File "/home/fap/.local/bin/git-privacy", line 11, in <module>
    load_entry_point('gitprivacy==2.1.0', 'console_scripts', 'git-privacy')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/fap/.local/lib/python3.8/site-packages/gitprivacy-2.1.0-py3.8.egg/gitprivacy/gitprivacy.py", line 273, in do_redate
  File "/home/fap/.local/lib/python3.8/site-packages/gitprivacy-2.1.0-py3.8.egg/gitprivacy/rewriter/amendrewriter.py", line 13, in rewrite
  File "/home/fap/.local/lib/python3.8/site-packages/gitprivacy-2.1.0-py3.8.egg/gitprivacy/encoder/__init__.py", line 37, in encode
  File "/home/fap/.local/lib/python3.8/site-packages/gitprivacy-2.1.0-py3.8.egg/gitprivacy/encoder/msgembed.py", line 32, in get_message_extra
  File "/home/fap/.local/lib/python3.8/site-packages/gitprivacy-2.1.0-py3.8.egg/gitprivacy/encoder/msgembed.py", line 77, in _encrypt_for_msg
  File "/home/fap/.local/lib/python3.8/site-packages/gitprivacy-2.1.0-py3.8.egg/gitprivacy/crypto/secretbox.py", line 23, in encrypt
AttributeError: 'EncryptedMessage' object has no attribute 'decodqe'
```

**Comment by cburkert** [comment]
@fapdash Looks like you accidentally edited the code somehow. Such that `decode` became `decodqe`? 
This typo is not upstream.

**Comment by fapdash** [comment]
Could verify that this fixes the issue, thank you!

**Review by fapdash — APPROVED** [review]

**Pull request merged**
